python:
  - 3.9.*
  - 3.10.*
python_impl:
  - cpython
  - cpython
numpy:
  - 1.20.*
  - 1.20.*
cudatoolkit:
  - 11.3.*
  - 11.3.*

docker_image: quay.io/condaforge/linux-anvil-cuda:11.3
channel_sources: https://conda.anaconda.org/t/$BINSTAR_TOKEN/ssnseawolf,pytorch,conda-forge,defaults
channel_targets: ssnseawolf main
